# Generated by Django 4.0.8 on 2022-11-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_planner", "0004_alter_route_route_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
