from locust import FastHttpUser, task, between

class fullTestUser(FastHttpUser):
#    wait_time = between(10, 15)

    @task()
    def api(self):
        self.client.get("/api/webcams/")
        self.client.get("/api/events/")
        self.client.get("/api/cms/ferries/")
        self.client.get("/api/cms/advisories/")
        self.client.get("/api/cms/bulletins/")
        self.client.get("/api/webcams/330/")

    @task()
    def cameras(self):
        self.client.get("/images/719.jpg")
        self.client.get("/images/945.jpg")
        self.client.get("/images/720.jpg")
        self.client.get("/images/797.jpg")
        self.client.get("/images/827.jpg")
        self.client.get("/images/695.jpg")
        self.client.get("/images/826.jpg")
        self.client.get("/images/853.jpg")
        self.client.get("/images/228.jpg")
        self.client.get("/images/446.jpg")
        self.client.get("/images/904.jpg")
        self.client.get("/images/912.jpg")
        self.client.get("/images/707.jpg")
        self.client.get("/images/852.jpg")
        self.client.get("/images/278.jpg")
        self.client.get("/images/297.jpg")
        self.client.get("/images/663.jpg")
        self.client.get("/images/109.jpg")
        self.client.get("/images/739.jpg")
        self.client.get("/images/703.jpg")
        self.client.get("/images/938.jpg")
        self.client.get("/images/957.jpg")
        self.client.get("/images/943.jpg")
        self.client.get("/images/939.jpg")
        self.client.get("/images/940.jpg")
        self.client.get("/images/949.jpg")
        self.client.get("/images/944.jpg")
        self.client.get("/images/952.jpg")
        self.client.get("/images/960.jpg")
        self.client.get("/images/941.jpg")
        self.client.get("/images/951.jpg")
        self.client.get("/images/947.jpg")
        self.client.get("/images/946.jpg")
        self.client.get("/images/955.jpg")
        self.client.get("/images/956.jpg")