#This script is mean to test users loading page (lot of stuff then cached), and moving around the site, with occasional API refresh.
from locust import FastHttpUser, task, between

class fullTestUser(FastHttpUser):

    @task(1)
    def initalLoad(self):
        self.client.get("/static/js/main.82121cbc.js")
        self.client.get("/static/css/main.b733ae68.css")
        self.client.get("/favicon.ico")
        self.client.get("/static/media/BCSans-Bold.252ecf87ea37c93b293c.woff")
        self.client.get("/static/media/BCSans-Regular.0079ea8e42d4e81a13d2.woff")
        self.client.get("/static/media/dbc-logo.db01b0c208d3fc8c9685639093aa724d.svg")
        self.client.get("/static/media/BCHwyCrest1.3250c217efd2de2b79cf66242614ec2b.svg")
        self.client.get("/static/media/BCHwyCrest.9291029e030864484ab6e32a1356dc1a.svg")
        self.client.get("/static/media/colocated-camera.db3f3531300ceed4b5c080dc1ae007ff.svg")
        self.client.get("/api/webcams/")
        self.client.get("/api/events/")
        self.client.get("/api/cms/ferries/")
        self.client.get("/api/cms/advisories/")
        self.client.get("/api/cms/bulletins/")

    @task(4)
    def cameraPage(self):
        self.client.get("/images/719.jpg")
        self.client.get("/images/945.jpg")
        self.client.get("/images/720.jpg")
        self.client.get("/images/797.jpg")
        self.client.get("/images/827.jpg")
        self.client.get("/images/695.jpg")
        self.client.get("/images/826.jpg")
        self.client.get("/images/853.jpg")
        self.client.get("/images/228.jpg")
        self.client.get("/images/446.jpg")
        self.client.get("/images/904.jpg")
        self.client.get("/images/912.jpg")
        self.client.get("/images/707.jpg")
        self.client.get("/images/852.jpg")
        self.client.get("/images/278.jpg")
        self.client.get("/images/297.jpg")
        self.client.get("/images/663.jpg")
        self.client.get("/images/109.jpg")
        self.client.get("/images/739.jpg")
        self.client.get("/images/703.jpg")
        self.client.get("/images/938.jpg")
        self.client.get("/images/957.jpg")
        self.client.get("/images/943.jpg")
        self.client.get("/images/939.jpg")
        self.client.get("/images/940.jpg")
        self.client.get("/images/949.jpg")
        self.client.get("/images/944.jpg")
        self.client.get("/images/952.jpg")
        self.client.get("/images/960.jpg")
        self.client.get("/images/941.jpg")
        self.client.get("/images/951.jpg")
        self.client.get("/images/947.jpg")
        self.client.get("/images/946.jpg")
        self.client.get("/images/955.jpg")
        self.client.get("/images/956.jpg")

        

    @task(7)
    def lookAroundMap(self):
        self.client.get("/images/719.jpg")
        self.client.get("/images/945.jpg")
        self.client.get("/images/720.jpg")
        self.client.get("/images/797.jpg")
        self.client.get("/images/827.jpg")
        self.client.get("/images/695.jpg")
        self.client.get("/images/826.jpg")
        self.client.get("/images/853.jpg")
        self.client.get("/images/228.jpg")
        self.client.get("/images/446.jpg")
        self.client.get("/images/904.jpg")
        self.client.get("/images/912.jpg")
        self.client.get("/images/707.jpg")
        self.client.get("/images/852.jpg")
        self.client.get("/images/278.jpg")
        self.client.get("/images/297.jpg")
        self.client.get("/images/663.jpg")
        self.client.get("/images/109.jpg")
        self.client.get("/images/739.jpg")
        self.client.get("/images/703.jpg")
        self.client.get("/django-media/original_images/lytton.jpg")
        self.client.get("/django-media/original_images/barnstonisland.jpg")
        self.client.get("/django-media/original_images/kootenaylakeosprey.jpg")
        self.client.get("/django-media/original_images/needlescable.jpg")

    @task(3)
    def reloadApi(self):
        self.client.get("/api/webcams/")
        self.client.get("/api/events/")
        self.client.get("/api/cms/ferries/")
        self.client.get("/api/cms/advisories/")
        self.client.get("/api/cms/bulletins/")

    @task(2)
    def openBulletinAdvisories(self):
        self.client.get("/django-media/images/workers-above-highway.width-500.png")
        self.client.get("/api/cms/advisories/17/")
        self.client.get("/django-media/original_images/Shift-Into-Winter-LOGO.jpg")
