from locust import FastHttpUser, task, between

class fullTestUser(FastHttpUser):
#    wait_time = between(10, 15)

    @task()
    def api(self):
        self.client.get("/api/webcams/")
        self.client.get("/api/events/")
        self.client.get("/api/cms/ferries/")
        self.client.get("/api/cms/advisories/")
        self.client.get("/api/cms/bulletins/")
        self.client.get("/api/webcams/330/")

    @task()
    def cameras(self):
        self.client.get("/webcam/api/v1/webcams/719/imageSource")
        self.client.get("/webcam/api/v1/webcams/945/imageSource")
        self.client.get("/webcam/api/v1/webcams/720/imageSource")
        self.client.get("/webcam/api/v1/webcams/797/imageSource")
        self.client.get("/webcam/api/v1/webcams/827/imageSource")
        self.client.get("/webcam/api/v1/webcams/695/imageSource")
        self.client.get("/webcam/api/v1/webcams/826/imageSource")
        self.client.get("/webcam/api/v1/webcams/853/imageSource")
        self.client.get("/webcam/api/v1/webcams/228/imageSource")
        self.client.get("/webcam/api/v1/webcams/446/imageSource")
        self.client.get("/webcam/api/v1/webcams/904/imageSource")
        self.client.get("/webcam/api/v1/webcams/912/imageSource")
        self.client.get("/webcam/api/v1/webcams/707/imageSource")
        self.client.get("/webcam/api/v1/webcams/852/imageSource")
        self.client.get("/webcam/api/v1/webcams/278/imageSource")
        self.client.get("/webcam/api/v1/webcams/297/imageSource")
        self.client.get("/webcam/api/v1/webcams/663/imageSource")
        self.client.get("/webcam/api/v1/webcams/109/imageSource")
        self.client.get("/webcam/api/v1/webcams/739/imageSource")
        self.client.get("/webcam/api/v1/webcams/703/imageSource")
        self.client.get("/webcam/api/v1/webcams/938/imageSource")
        self.client.get("/webcam/api/v1/webcams/957/imageSource")
        self.client.get("/webcam/api/v1/webcams/943/imageSource")
        self.client.get("/webcam/api/v1/webcams/939/imageSource")
        self.client.get("/webcam/api/v1/webcams/940/imageSource")
        self.client.get("/webcam/api/v1/webcams/949/imageSource")
        self.client.get("/webcam/api/v1/webcams/944/imageSource")
        self.client.get("/webcam/api/v1/webcams/952/imageSource")
        self.client.get("/webcam/api/v1/webcams/960/imageSource")
        self.client.get("/webcam/api/v1/webcams/941/imageSource")
        self.client.get("/webcam/api/v1/webcams/951/imageSource")
        self.client.get("/webcam/api/v1/webcams/947/imageSource")
        self.client.get("/webcam/api/v1/webcams/946/imageSource")
        self.client.get("/webcam/api/v1/webcams/955/imageSource")
        self.client.get("/webcam/api/v1/webcams/956/imageSource")

