name: Build and publish image to openshift

on:
  push:
    branches: [ "main" ]
    paths-ignore: "azure-locust/**"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build Docker image
    environment: main

    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: build backend
        uses: redhat-actions/buildah-build@v2
        with:
          image: locust
          tags: latest ${{ github.sha }}
          labels: |
            app=locust
          containerfiles: ./Dockerfile

      - name: push to gold registry
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: locust
          registry: ${{ secrets.GOLD_REGISTRY }}
          username: ${{ secrets.GOLD_BUILDER_USERNAME }}
          password: ${{ secrets.GOLD_BUILDER_TOKEN }}
